;;; eshell-git-prompt-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from eshell-git-prompt.el

(autoload 'eshell-git-prompt-use-theme "eshell-git-prompt" "\
Pick up a Eshell prompt theme from `eshell-git-prompt-themes' to use.

(fn THEME)" t)
(autoload 'eshell/use-theme "eshell-git-prompt" "\
List all available themes and pick one from Eshell.

(fn &optional THEME)")
(register-definition-prefixes "eshell-git-prompt" '("eshell-git-prompt-" "with-face"))

;;; End of scraped data

(provide 'eshell-git-prompt-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; eshell-git-prompt-autoloads.el ends here
