;;; lsp-latex.el-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from lsp-latex.el

(autoload 'lsp-latex-forward-search-with-pdf-tools "lsp-latex" "\
Forward search with pdf-tools, from TEX-FILE line LINE to PDF-FILE.
This function is partially copied from
`pdf-sync-forward-search' and `pdf-sync-forward-correlate'.

(fn TEX-FILE PDF-FILE LINE)")
(register-definition-prefixes "lsp-latex" '("lsp-latex-"))

;;; End of scraped data

(provide 'lsp-latex.el-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; lsp-latex.el-autoloads.el ends here
