;;; harpoon.el-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from harpoon.el

(autoload 'harpoon-go-to "harpoon" "\
Go to specific file on harpoon (by line order). LINE-NUMBER: Line to go.

(fn LINE-NUMBER)")
(autoload 'harpoon-delete-1 "harpoon" "\
Delete item harpoon on position 1." t)
(autoload 'harpoon-delete-2 "harpoon" "\
Delete item harpoon on position 1." t)
(autoload 'harpoon-delete-3 "harpoon" "\
Delete item harpoon on position 1." t)
(autoload 'harpoon-delete-4 "harpoon" "\
Delete item harpoon on position 1." t)
(autoload 'harpoon-delete-5 "harpoon" "\
Delete item harpoon on position 1." t)
(autoload 'harpoon-delete-6 "harpoon" "\
Delete item harpoon on position 1." t)
(autoload 'harpoon-delete-7 "harpoon" "\
Delete item harpoon on position 1." t)
(autoload 'harpoon-delete-8 "harpoon" "\
Delete item harpoon on position 1." t)
(autoload 'harpoon-delete-9 "harpoon" "\
Delete item harpoon on position 1." t)
(autoload 'harpoon-go-to-1 "harpoon" "\
Go to file 1 on harpoon." t)
(autoload 'harpoon-go-to-2 "harpoon" "\
Go to file 2 on harpoon." t)
(autoload 'harpoon-go-to-3 "harpoon" "\
Go to file 3 on harpoon." t)
(autoload 'harpoon-go-to-4 "harpoon" "\
Go to file 4 on harpoon." t)
(autoload 'harpoon-go-to-5 "harpoon" "\
Go to file 5 on harpoon." t)
(autoload 'harpoon-go-to-6 "harpoon" "\
Go to file 6 on harpoon." t)
(autoload 'harpoon-go-to-7 "harpoon" "\
Go to file 7 on harpoon." t)
(autoload 'harpoon-go-to-8 "harpoon" "\
Go to file 8 on harpoon." t)
(autoload 'harpoon-go-to-9 "harpoon" "\
Go to file 9 on harpoon." t)
(autoload 'harpoon-add-file "harpoon" "\
Add current file to harpoon." t)
(autoload 'harpoon-quick-menu-hydra "harpoon" "\
Open harpoon quick menu with hydra." t)
(autoload 'harpoon-delete-item "harpoon" "\
Delete items on harpoon." t)
(autoload 'harpoon-toggle-file "harpoon" "\
Open harpoon file." t)
(autoload 'harpoon-toggle-quick-menu "harpoon" "\
Open quickmenu." t)
(autoload 'harpoon-clear "harpoon" "\
Clear harpoon files." t)
(autoload 'harpoon-find-file "harpoon" "\
Visit file on `harpoon-mode'." t)
(register-definition-prefixes "harpoon" '("harpoon-"))

;;; End of scraped data

(provide 'harpoon.el-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; harpoon.el-autoloads.el ends here
