;;; lsp-haskell-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from lsp-haskell.el

(register-definition-prefixes "lsp-haskell" '("lsp-haskell-"))

;;; End of scraped data

(provide 'lsp-haskell-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; lsp-haskell-autoloads.el ends here
