;;; statusbar.el-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from statusbar.el

(register-definition-prefixes "statusbar" '("battery-statusbar-string" "brightness-" "display-" "statusbar-" "symbol-concat" "volume-update" "wifi-update"))

;;; End of scraped data

(provide 'statusbar.el-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; statusbar.el-autoloads.el ends here
