#!/bin/sh

if [ -z "$1" ] ; then
    echo "usage: bgimageset [options] <color/image file>"
    echo "options can be any of the feh background settings"
elif [ -z "$2" ] ; then
    firstchar=$(echo "$1" | cut -b 1)
    if [ "$firstchar" = "#" ]; then
        pkill -x xcompmgr
        xsetroot -solid "$1"
    else
        feh --bg-center "$1"
    fi
else
    feh "$1" "$2"
fi
