#!/bin/sh

WALLPAPER_DIR=$HOME/wallpapers
files=$(find $WALLPAPER_DIR -type f)
choices="$(parallel 'file {} | grep image 1>/dev/null && basename {}' ::: $files)"

UEBERZUG_TMP_DIR="/tmp"

cleanup() {
    ueberzugpp cmd -s "$SOCKET" -a exit
}
trap cleanup HUP INT QUIT TERM EXIT

UB_PID_FILE="$UEBERZUG_TMP_DIR/.$(uuidgen)"
ueberzugpp layer --no-stdin --silent --use-escape-codes --pid-file "$UB_PID_FILE"
UB_PID=$(cat "$UB_PID_FILE")

export SOCKET="$UEBERZUG_TMP_DIR"/ueberzugpp-"$UB_PID".socket

# run fzf with preview
file=$(echo $choices | tr ' ' '\n' |
    fzf --reverse --preview="ueberzugpp cmd -s $SOCKET -i fzfpreview -a add \
    -x \$FZF_PREVIEW_LEFT -y \$FZF_PREVIEW_TOP \
    --max-width \$FZF_PREVIEW_COLUMNS --max-height \$FZF_PREVIEW_LINES \
    -f $WALLPAPER_DIR/{}")
ueberzugpp cmd -s "$SOCKET" -a exit

if [ -z $file ]; then
    exit 1
fi

cd $WALLPAPER_DIR
ln -sfn $file current_wallpaper
pkill -x hyprpaper
hyprpaper 2>&1 1>/dev/null &
