#!/bin/sh
if [ -z "$1" ] ; then
    echo "usage: $0 [output file]"
    exit 1
fi
temp="$(mktemp list-deps.XXXXXX)"
list="$(equery --quiet --nocolor list '*')"
output=$(parallel 'a=$(equery --quiet --nocolor depgraph {} | tail -n+3 | wc -l); \
 printf "%s %s\n" $a {}' ::: $list 2>/dev/null > "$temp")
sort -nr "$temp" > $1
rm "$temp"
