#!/bin/sh

pgrep -x dmenu && exit

mountable=$(lsblk -lp | grep "part $" | awk '{print $1, "(" $4 ")"}')
if [ "$mountable" = "" ]; then exit 1; fi
chosen=$(echo "$mountable" | dmenu -i -p "Mount which drive?" | awk '{print $1}') > /dev/null
if [ "$chosen"  = "" ]; then  exit 1; fi

dirs=$(find /mnt /media /mount /home -type d -maxdepth 3 2>/dev/null)
mountpoint=$(echo "$dirs" | dmenu -i -p "Type in mount point ")
if [ "$mountpoint" = "" ]; then exit 1; fi
if [ ! -d "$mountpoint" ]; then
    mkdiryn=$(printf "No\nYes" | dmenu -i -p "$mountpoint does not exist. Create it?")
    if [ "$mkdiryn" = "Yes" ]; then sudo -A mkdir -p "$mountpoint"; fi
fi
sudo -A mount $chosen $mountpoint && pgrep -x dunst && notify-send "$chosen mounted to $mountpoint."
