#!/bin/bash
CONFIG_FILE_NAME="tmux-sessionizer.conf"
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/tmux-sessionizer"
CONFIG_FILE="$CONFIG_DIR/$CONFIG_FILE_NAME"

if [ -f "$CONFIG_FILE" ]; then
    source "$CONFIG_FILE"
fi

if [ -f "$CONFIG_FILE_NAME" ]; then
    source "$CONFIG_FILE_NAME"
fi

emacsclient -e '(message "")' 2>&1 >/dev/null || emacs --daemon &

find_dirs() {
    # paths=$(for path in "${TS_SEARCH_PATHS[@]}"; do
    #             [[ -d "$path" ]] && find "$path" -mindepth 2 -maxdepth 2 -path '*/.git' -prune -o -type d -print
    #         done)
    # eval other_projects=$(emacsclient -e "(proj-previously-opened)")
    # if [ "$other_projects" != "nil" ]; then
    #     for f in "${other_projects[@]}"; do
    #         echo "EMACS ${f%/}"
    #     done
    # fi
    # for x in ${paths}; do
    #     echo "~/${x#/*/*/}"
    # done
    eval paths=$(emacsclient -e "(proj--get-paths)")
    for x in "${paths[@]}"; do
        echo "$x"
    done
}

emacs_attached() {
    [ "$(emacsclient -e '(- (length (frame-list)) 1)')" = 0 ] && return 1 || return 0
}

switch_to() {
    if emacs_attached; then
        emacsclient -e "(proj-set \"$1\")"
    else
        emacsclient -ce "(proj-set \"$1\")"
    fi
}

selected=$(find_dirs | sort -Ru | swenu -coil 15)
[ -z "$selected" ] && exit 1;

if [ ! -z "$(echo $selected | grep '^EMACS')" ]; then
    selected=$(echo "$selected" | sed 's,^EMACS \(.*\)$,\1,')
fi

selected="${selected/\~/$HOME}"
switch_to "$selected"

client=$(hyprctl -j clients | jq '.[] | select(.class == "emacs")')
workspace=$(echo ${client} | jq -r '.workspace.id')
address=$(echo ${client} | jq -r '.address')

hyprctl --batch "dispatch workspace $workspace ; dispatch focuswindow address:$address" 1>/dev/null
