#!/bin/sh
backlightctrl -set 10
gpgconf -K gpg-agent
restartsearxng &
restartemacs >/dev/null &
pipewire &
mpd &
dunst &
xss-lock swaylock &
waybar &
gpg-agent --options ~/.gnupg/gpg-agent-wayland.conf --daemon
