#!/bin/bash
sleep 1
killall xdg-desktop-portal-hyprland
killall xdg-desktop-portal-gtk
killall xdg-desktop-portal-gnome
killall xdg-desktop-portal-wlr
killall xdg-desktop-portal

sleep 1
# if [ -z "$WINDOWMANAGER" ] || [ "$WINDOWMANAGER" = "d" ] ; then
#     /usr/libexec/xdg-desktop-portal-wlr &
# else
    /usr/libexec/xdg-desktop-portal-hyprland &
# fi

sleep 1
/usr/libexec/xdg-desktop-portal-gtk &

sleep 1
/usr/libexec/xdg-desktop-portal &
