[colors]
draw_bold_text_with_bright_colors = false

[colors.primary]
background = "#000000"

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "alacritty"

[font]
size = 10.6

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
style = "Regular"

[font.normal]
family = "DejaVu Sans Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[[hints.enabled]]
command = "wl-copy"
hyperlinks = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[[keyboard.bindings]]
action = "None"
key = "I"
mods = "Super"

[scrolling]
history = 10000

[window]
decorations = "none"
decorations_theme_variant = "None"
dynamic_padding = false
dynamic_title = true
opacity = 1.0
resize_increments = false
startup_mode = "Windowed"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 3
y = 3
